//
//  Configuration.m
//  BATester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07-18-2016
//
#import "Configuration.h"

/** The base Uri for API calls */
NSString* Configuration_BaseUri = @"http://www.an-actual-website.com";

/** The username to use with basic authentication */
/** Replace the value of BasicAuthUserName with an appropriate value */
NSString* Configuration_BasicAuthUserName = @"TODO: Replace";

/** The password to use with basic authentication */
/** Replace the value of BasicAuthPassword with an appropriate value */
NSString* Configuration_BasicAuthPassword = @"TODO: Replace";

