//
//  APIController.h
//  BATester
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/18/2016
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface APIController : BaseController

/**
* Completion block definition for asynchronous call to BasicAuthTest */
typedef void (^CompletedGetBasicAuthTest)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* TODO: type endpoint description here
*/
- (void) getBasicAuthTestWithCompletionBlock:(CompletedGetBasicAuthTest) onCompleted;

@end